markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: src/scss
  style: compressed

base_path: 'demo'

title: 即刻出发
author :
  name : wy-ei
  email : nameiswangyu@163.com
  github : wy-ei
